// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATB9-wH5bWewwDgw-Q5RsTdsBcNXqzMEI',
    appId: '1:453163281429:web:61f57e8807fa697adff21c',
    messagingSenderId: '453163281429',
    projectId: 'e-commerce-mobile-app-49118',
    authDomain: 'e-commerce-mobile-app-49118.firebaseapp.com',
    storageBucket: 'e-commerce-mobile-app-49118.firebasestorage.app',
    measurementId: 'G-P0QZKV4DNQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSsvg9EkIDwuZ0STaYwwouQgNZZMbxrrI',
    appId: '1:453163281429:android:efa80e0f4401295cdff21c',
    messagingSenderId: '453163281429',
    projectId: 'e-commerce-mobile-app-49118',
    storageBucket: 'e-commerce-mobile-app-49118.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqZ9xBNvlhxFoVq9COw7qOAl-3zha_mO0',
    appId: '1:453163281429:ios:250c32efc1a7281edff21c',
    messagingSenderId: '453163281429',
    projectId: 'e-commerce-mobile-app-49118',
    storageBucket: 'e-commerce-mobile-app-49118.firebasestorage.app',
    iosClientId: '453163281429-g15iphqi9f5t25ftcg1f51s53fvelocr.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopSmart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqZ9xBNvlhxFoVq9COw7qOAl-3zha_mO0',
    appId: '1:453163281429:ios:250c32efc1a7281edff21c',
    messagingSenderId: '453163281429',
    projectId: 'e-commerce-mobile-app-49118',
    storageBucket: 'e-commerce-mobile-app-49118.firebasestorage.app',
    iosClientId: '453163281429-g15iphqi9f5t25ftcg1f51s53fvelocr.apps.googleusercontent.com',
    iosBundleId: 'com.example.shopSmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATB9-wH5bWewwDgw-Q5RsTdsBcNXqzMEI',
    appId: '1:453163281429:web:a47b2501093e0087dff21c',
    messagingSenderId: '453163281429',
    projectId: 'e-commerce-mobile-app-49118',
    authDomain: 'e-commerce-mobile-app-49118.firebaseapp.com',
    storageBucket: 'e-commerce-mobile-app-49118.firebasestorage.app',
    measurementId: 'G-LCHJ5PXQF6',
  );

}